### ISSUE TITLE
Keyboard support. 

### ISSUE THREAD

**Issue by jakub-swierk** [MopTym/doSlide#13]
How about add support for keyboard navigation?

**Comment by MopTym** [comment]
Sounds great, I will add it.

**Comment by MopTym** [comment]
Keyboard event is different from the mouse wheel event nor the swipe event, I encapsulate it in the form of a build-in plugin ([src/plugins/keyboard](https://github.com/MopTym/doSlide/tree/dev/src/plugins/keyboard)).

**Comment by jakub-swierk** [comment]
Wow, thanks!

For my purposes i use little different mapping:

``` coffeescript
mapping = [
    {
        filter: isPressed([32,34,40]), #space, pgdown, arrow-down
        action: () -> this.next()
    },
    {
        filter: isPressed([33,38]),   #pgup, arrow-up
        action: () -> this.prev()
    },
    {
        filter: isPressed([36]),      #home
        action: () -> this.go(0)
    },
    {
        filter: isPressed([35]),      #end
        action: () -> this.go(this.sections.length - 1)
    }
]
```

**Comment by MopTym** [comment]
Great, your mapping is more comprehensive for fullpage scrolling. The default mapping is the most basic one.
