### ISSUE TITLE
Strange behavior on mac touchboard

### ISSUE THREAD

**Issue by Piasy** [MopTym/doSlide#17]
![1](https://cloud.githubusercontent.com/assets/3098704/12663419/116cc880-c663-11e5-9c0f-68d2236ce2f4.gif)

As the posted gif above, when I scroll down, the slide may slide up, even when I just touch the pad, it also scrolls up. My touchboard works well in other apps/web pages.

**Comment by MopTym** [comment]
Thanks for your feedback. 

I didn't consider the scrolling behavior on Mac touch board before. It works well when user uses PC notebook's touch board or mouse wheel to scroll pages. 

An interval has been added between mouse wheel events in this demo:  

http://app.moptym.com/do-slide/demo/touch-board/

Is there still the problem? By the way, I think most of Mac users may scroll pages with two fingers, your gesture is different in the gif.

**Comment by Piasy** [comment]
The new demo still has the same problem, and it's even worse. It couldn't detect scroll easily.

By the way, I do use two fingers to scroll, maybe it doesn't look clearly from the gif.

**Comment by MopTym** [comment]
Does fullPage.js have the same problem? http://alvarotrigo.com/fullPage/

**Comment by Piasy** [comment]
No, it works perfect.

**Comment by MopTym** [comment]
OK, I will take time to solve it.

**Comment by MopTym** [comment]
I did some improvement, now this demo should be OK: 

http://app.moptym.com/do-slide/demo/touch-board-2/

**Comment by Piasy** [comment]
It works like a charm!
