### ISSUE TITLE
use navbar

### ISSUE THREAD

**Issue by paulcalvet** [MopTym/doSlide#22]
Hi,
I have a Navbar in my first section, I want to go to a specific section when I click on a navbar link.
Is it possible ? I tried to use the go(index) function but I did not succeed.

Thanks a lot for your great module.

Paul

**Comment by MopTym** [comment]
Yes it's possible, could you provide a reproduction?

**Comment by paulcalvet** [comment]
Yes sure !

This is the link in my code to go to another sections, it works, when you click you go to the section but after you can't go to another section.
`<li><a href="#Dashboard" class="philharmonie">Dashboard</a></li>`

Here is the full page :
[0_0_basic.txt](https://github.com/MopTym/doSlide/files/461213/0_0_basic.txt)

Thanks you.

**Comment by MopTym** [comment]
Hash doesn't work, you need to manually call `slide.go(index)` , for example: 

change `<li><a href="#Dashboard" class="philharmonie">Dashboard</a></li>`
to `<li><a href="javascript:void(0)" onclick="slide.go(1)" class="philharmonie">Dashboard</a></li>`

It's better to use `addEventListener` or `.on()` in jQuery.

**Comment by paulcalvet** [comment]
That works very well !
Thank you.
