### ISSUE TITLE
How to know the slide section index

### ISSUE THREAD

**Issue by paulcalvet** [MopTym/doSlide#23]
Hi,
I want to change the property of my navbar when the user change scroll.
On the first slide the navbar background is transparent and when I slide, I want to change the color.

I want to use the currentIndex property of the slide like this : 

`DoSlide.$.onMouseWheel(document.body, function(direction) {

```
            if(slide.currentIndex=0){
            var cols = document.getElementsByClassName('navbar');
            for(i=0; i<cols.length; i++) {
            cols[i].style.backgroundColor =    'transparent';}
            }

            if(slide.currentIndex>1){
            var cols = document.getElementsByClassName('navbar');
            for(i=0; i<cols.length; i++) {
            cols[i].style.backgroundColor =    'white';}
            }

            console.log(direction)
           console.log(slide.currentIndex)
        })`
```

The problem is that the currentIndex property is always set to 1, Even when I slide. Is it normal ?
Thanks !

Paul

**Comment by MopTym** [comment]
`onMouseWheel` may be triggered multiple times when you change section, use `onBeforeChange` or `onChanged` is better.

``` js
slide.onBeforeChange(function (curIndex, tarIndex, cur, tar) {
  console.log('START: ', 'from', curIndex, 'to', tarIndex)
})
slide.onChanged(function (curIndex, lastIndex, cur, last) {
  console.log('END: ', 'from', lastIndex, 'to', curIndex)
})
```

**Comment by paulcalvet** [comment]
It works very well with this functions.
Thank you very much !
